INDIVIDUAL_IMAGE_TIMER = 2.0
INDIVIDUAL_RATING_TIMER = 2.0

TEAM_IMAGE_TIMER = 5.0 #Team task where they cannot dicuss 
DISCUSSION_TIMER = 10.0 #Team task where they have to dicuss 
TEAM_RATING_TIMER = 5.0

BLANK_SCREEN_MILLISECONDS = 1000
CROSS_SCREEN_MILLISECONDS = 500


DISPLAY_MSG_AFFEC_DISCUSSION = 3000 