from config import BLANK_SCREEN_COUNT_DOWN_MILLISECONDS


INDIVIDUAL_IMAGE_TIMER = 15.0
INDIVIDUAL_RATING_TIMER = 15.0

TEAM_IMAGE_TIMER = 25.0
TEAM_RATING_TIMER = 25.0

BLANK_SCREEN_MILLISECONDS = 1000
CROSS_SCREEN_MILLISECONDS = 500
