from .utils import WINDOW_HEIGHT, WINDOW_WIDTH

PADDLE_WIDTH = 20
PADDLE_HEIGHT = 120

CENTER_Y = int((WINDOW_HEIGHT + PADDLE_HEIGHT) / 2)
INITIAL_POSITION_LEFT = (0, CENTER_Y)
INITIAL_POSITION_RIGHT = (WINDOW_WIDTH - PADDLE_WIDTH, CENTER_Y)

UPPER_BOUND = WINDOW_HEIGHT - PADDLE_HEIGHT

SPEED_SCALING = 0.6
MAX_SPEED = None

BALL_X_SPEED = 12
BALL_BOUNCE_ON_PADDLE_SCALE = 0.35
