from .utils import WINDOW_HEIGHT

PADDLE_WIDTH = 20
PADDLE_HEIGHT = 120

UPPER_BOUND = WINDOW_HEIGHT - PADDLE_HEIGHT

SPEED_SCALING = 0.6
MAX_SPEED = None

BALL_X_SPEED = 12
BALL_BOUNCE_ON_PADDLE_SCALE = 0.30
