from .exit_instruction import exit_instruction
from .finger_tapping_task_instruction import finger_tapping_task_instruction
from .ping_pong_task_competitive_instruction import ping_pong_task_competitive_instruction
from .ping_pong_task_cooperative_instruction import ping_pong_task_cooperative_instruction
